# Generated by Django 4.2.2 on 2023-06-23 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bot", "0002_speach"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetupuser",
            name="is_speaker",
            field=models.BooleanField(default=False, verbose_name="Докладчик"),
        ),
        migrations.AlterField(
            model_name="meetupuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
