# Generated by Django 4.2.2 on 2023-06-23 13:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_alter_meetupuser_is_speaker_alter_meetupuser_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetupuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                db_index=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Номер владельца",
            ),
        ),
    ]
