# Generated by Django 4.2.2 on 2023-06-24 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bot", "0004_meetupuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetupuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                db_index=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="speach",
            name="end_at",
            field=models.DateTimeField(verbose_name="Окончание"),
        ),
        migrations.AlterField(
            model_name="speach",
            name="start_at",
            field=models.DateTimeField(verbose_name="Начало"),
        ),
        migrations.CreateModel(
            name="Qustion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="Вопрос")),
                (
                    "speach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qustions",
                        to="bot.speach",
                        verbose_name="К докладу",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(
                        related_name="qustions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто задал вопрос",
                    ),
                ),
            ],
        ),
    ]
