# Generated by Django 4.2.2 on 2023-06-25 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bot", "0005_alter_meetupuser_phone_alter_speach_end_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="Вопрос")),
                (
                    "speach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="bot.speach",
                        verbose_name="К докладу",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто задал вопрос",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Qustion",
        ),
    ]
